/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ppt;

/**
 *
 * @author Pedro
 */
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.util.Random;
import java.io.FileInputStream;
import java.io.InputStream;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

public class Principal extends javax.swing.JFrame {
    static Random r = new Random();
    static int Ganadas = 0;
    static int Empates = 0;
    static int Perdidas = 0;
    
    /**
     * Creates new form Principal
     */
    Font font = new Font("Agency FB", Font.BOLD, 60);
    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Papel = new javax.swing.JButton();
        Tijera = new javax.swing.JButton();
        Piedra = new javax.swing.JButton();
        Resultado = new javax.swing.JLabel();
        JugadaRobo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JEmpate = new javax.swing.JLabel();
        JGanadas = new javax.swing.JLabel();
        JPerdidas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/papel-slide.png"))); // NOI18N
        Papel.setBorderPainted(false);
        Papel.setContentAreaFilled(false);
        Papel.setDoubleBuffered(true);
        Papel.setFocusPainted(false);
        Papel.setRequestFocusEnabled(false);
        Papel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PapelActionPerformed(evt);
            }
        });
        getContentPane().add(Papel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        Tijera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/tijera-slide.png"))); // NOI18N
        Tijera.setBorderPainted(false);
        Tijera.setContentAreaFilled(false);
        Tijera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TijeraActionPerformed(evt);
            }
        });
        getContentPane().add(Tijera, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, -1, -1));

        Piedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/piedra-slide.png"))); // NOI18N
        Piedra.setBorderPainted(false);
        Piedra.setContentAreaFilled(false);
        Piedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiedraActionPerformed(evt);
            }
        });
        getContentPane().add(Piedra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        getContentPane().add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 410, 90));
        getContentPane().add(JugadaRobo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 230, 100));

        jLabel3.setFont(new java.awt.Font("Tekton Pro Cond", 2, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 204));
        jLabel3.setText("Empates:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, 40));

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("ROBOT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tekton Pro Cond", 2, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 0));
        jLabel4.setText("Puntuación ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 150, 40));

        jLabel5.setFont(new java.awt.Font("Tekton Pro Cond", 2, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 204));
        jLabel5.setText("Ganadas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, 40));

        jLabel6.setFont(new java.awt.Font("Tekton Pro Cond", 2, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 204));
        jLabel6.setText("Perdidas:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 150, 40));

        JEmpate.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        JEmpate.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(JEmpate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 130, 40));

        JGanadas.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        JGanadas.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(JGanadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 130, 40));

        JPerdidas.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        JPerdidas.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(JPerdidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/5770e4ccb2b3d.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PapelActionPerformed
        Escribir(Resultado('A', Robo()));
        EscribirPuntuacion();
    }//GEN-LAST:event_PapelActionPerformed

    private void TijeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TijeraActionPerformed
        Escribir(Resultado('T', Robo()));
        EscribirPuntuacion();
    }//GEN-LAST:event_TijeraActionPerformed

    private void PiedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiedraActionPerformed
        Escribir(Resultado('P', Robo()));
        EscribirPuntuacion();
    }//GEN-LAST:event_PiedraActionPerformed
    public void SonidoDay(String res){
         if(res.equalsIgnoreCase("Ganaste")){
            
                      PlayMusic("C:\\Users\\Pedro\\Documents\\NetBeansProjects\\PPT\\Sonidos\\Ganaste2.wav");
         }
         else{
             if(res.equalsIgnoreCase("Perdiste")){
                PlayMusic("C:\\Users\\Pedro\\Documents\\NetBeansProjects\\PPT\\Sonidos\\Perdiste2.wav");
             }
             else{
                 System.out.println("E");
                 PlayMusic("C:\\Users\\Pedro\\Documents\\NetBeansProjects\\PPT\\Sonidos\\Empate2.wav");
             }
         }
    }
    public static void PlayMusic(String filepath){
        InputStream music;
        try{
            music = new FileInputStream(new File(filepath));
            AudioStream audios = new AudioStream(music);
            AudioPlayer.player.start(audios);
        }
        catch(Exception e){
            System.out.println("ERROR" + e);
        }
    }
    public void EscribirPuntuacion(){
        JGanadas.setText(Ganadas + "");
        JPerdidas.setText(Perdidas + "");
        JEmpate.setText(Empates + "");
    }
    public void Escribir(String res){
        Resultado.setFont(font);
        Resultado.setForeground(Color.red);
        Resultado.setText(res);
    }
    public String Resultado(char Jugador, char robo){
        String resultado= "";
        if(Jugador == 'P'){
            if(robo == 'P'){
                resultado = "Empate";
                Empates++;
            }
            else{
                if(robo == 'A'){
                    resultado = "Perdiste";
                    Perdidas++;
                    
                }
                else{
                    resultado = "Ganaste";
                    Ganadas++;
                }
            }
        }
        if(Jugador == 'A'){
            if(robo == 'P'){
                resultado = "Ganaste";
                Ganadas++;
            }
            else{
                if(robo == 'A'){
                    resultado = "Empate";
                    Empates++;
                }
                else{
                    resultado = "Perdiste";
                    Perdidas++;
                }
            }
        }
        if(Jugador == 'T'){
            if(robo == 'P'){
                resultado = "Perdiste";
                Perdidas++;
            }
            else{
                if(robo == 'A'){
                    resultado = "Ganaste";
                    Ganadas++;
                }
                else{
                    resultado = "Empate";
                    Empates++;
                }
            }
        }
        SonidoDay(resultado);
        return resultado;
        
    
    }
    public char Robo(){
        JugadaRobo.setFont(font);
        JugadaRobo.setForeground(Color.yellow);
        int num = r.nextInt(3)+1;
        if(num == 1){
            JugadaRobo.setText("Piedra");
            return 'P';       
        }
        else{
            if(num ==2){
                JugadaRobo.setText("Papel");
                return 'A';
            }
            else{
                JugadaRobo.setText("Tijera");
                return 'T';
            }
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JEmpate;
    private javax.swing.JLabel JGanadas;
    private javax.swing.JLabel JPerdidas;
    private javax.swing.JLabel JugadaRobo;
    private javax.swing.JButton Papel;
    private javax.swing.JButton Piedra;
    private javax.swing.JLabel Resultado;
    private javax.swing.JButton Tijera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables


}
